[package]
name = "quant_de"
version = "0.1.0"
authors = ["Jay Woodhill <jay.woodhill1@gmail.com"]
edition = "2024"
description = "Low-latency API for ASX Signal B Data Feed emulation"
license = "MIT"
repository = "https://github.com/JayWoodhill/quant_de"
homepage = "https://github.com/JayWoodhill/quant_de"
documentation = TBA
readme = "docs/readme.rst"
keywords = ["rust", "api", "FIX", "low-latency", "ASX", "trading", "market data"]
categories = ["network-programming", "data-processing", "trading", "data-engineering"]

[dependencies]
# Web framework for building the API
warp = "0.3"
tokio = { version = "1", features = ["full"] }

# Serialization / Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# TLS for encrypted connections
rustls = "0.20"
tokio-rustls = "0.23"

# Logging
log = "0.4"
env_logger = "0.10"

# For cryptography (optional, if needed for secure handling)
ring = "0.16"

# For time handling
chrono = "0.4"

[dev-dependencies]
# Dependencies for testing
tokio-test = "0.4"
assert_json_diff = "2.0"   # For testing JSON outputs

[features]
default = ["tls", "logging"]
tls = ["rustls", "tokio-rustls"]
logging = ["env_logger"]
