FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY src/ src/

EXPOSE 443

CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile=key.pem", "--ssl-certfile=cert.pem"]
